nodeLinker: node-modules
enableGlobalCache: false
supportedArchitectures: { os: ["darwin"], cpu: ["arm64"], libc: ["glibc"] }
compressionLevel: 4
npmAuditRegistry: "https://registry.npmjs.org/"
progressBarStyle: "jack"
